name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Get version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build binaries
        run: |
          # Build for multiple platforms
          GOOS=linux GOARCH=amd64 go build -o bpl-tools-linux-amd64 .
          GOOS=windows GOARCH=amd64 go build -o bpl-tools-windows-amd64.exe .
          GOOS=darwin GOARCH=amd64 go build -o bpl-tools-darwin-amd64 .
          GOOS=darwin GOARCH=arm64 go build -o bpl-tools-darwin-arm64 .

      - name: Create release packages
        run: |
          # Create temporary directories for each platform with proper folder structure
          mkdir -p bpl-tools-linux/bpl-tools
          mkdir -p bpl-tools-windows/bpl-tools
          mkdir -p bpl-tools-darwin-amd64/bpl-tools
          mkdir -p bpl-tools-darwin-arm64/bpl-tools

          # Copy binaries to platform-specific directories
          cp bpl-tools-linux-amd64 bpl-tools-linux/bpl-tools/bpl-tools
          cp bpl-tools-windows-amd64.exe bpl-tools-windows/bpl-tools/bpl-tools.exe
          cp bpl-tools-darwin-amd64 bpl-tools-darwin-amd64/bpl-tools/bpl-tools
          cp bpl-tools-darwin-arm64 bpl-tools-darwin-arm64/bpl-tools/bpl-tools

          # Create zip archives with folder structure
          zip -r bpl-tools-${{ steps.version.outputs.VERSION }}-linux-amd64.zip bpl-tools-linux/
          zip -r bpl-tools-${{ steps.version.outputs.VERSION }}-windows-amd64.zip bpl-tools-windows/
          zip -r bpl-tools-${{ steps.version.outputs.VERSION }}-darwin-amd64.zip bpl-tools-darwin-amd64/
          zip -r bpl-tools-${{ steps.version.outputs.VERSION }}-darwin-arm64.zip bpl-tools-darwin-arm64/

          # Clean up temporary directories
          rm -rf bpl-tools-linux bpl-tools-windows bpl-tools-darwin-amd64 bpl-tools-darwin-arm64

      - name: Generate release notes
        id: release_notes
        run: |
          cat > release_notes.md << 'EOF'
          ## BPL Tools ${{ steps.version.outputs.VERSION }}

          ### Quick Start
          1. Download the appropriate zip file for your platform below
          2. Extract the zip file - this will create a `bpl-tools` folder
          3. Navigate to the `bpl-tools` folder
          4. Run the tool: `./bpl-tools` (Linux/macOS) or `bpl-tools.exe` (Windows)
          5. The application will automatically prompt you for any required credentials when you first use each feature
          6. Configuration will be saved in `bpl-config.txt` in the same folder

          ### Features
          - **Check Player Names**: Verify player names contain team abbreviations (no credentials required)
          - **Handle Private League Invites**: Automatically process private league invitations  
          - **Guild Stash Monitor**: Monitor guild stash changes and sync to BPL backend

          ### Platform Downloads
          - **Windows**: `bpl-tools-${{ steps.version.outputs.VERSION }}-windows-amd64.zip`
          - **Linux**: `bpl-tools-${{ steps.version.outputs.VERSION }}-linux-amd64.zip`  
          - **macOS Intel**: `bpl-tools-${{ steps.version.outputs.VERSION }}-darwin-amd64.zip`
          - **macOS Apple Silicon**: `bpl-tools-${{ steps.version.outputs.VERSION }}-darwin-arm64.zip`
          EOF

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          name: BPL Tools ${{ steps.version.outputs.VERSION }}
          body_path: release_notes.md
          files: |
            bpl-tools-${{ steps.version.outputs.VERSION }}-linux-amd64.zip
            bpl-tools-${{ steps.version.outputs.VERSION }}-windows-amd64.zip
            bpl-tools-${{ steps.version.outputs.VERSION }}-darwin-amd64.zip
            bpl-tools-${{ steps.version.outputs.VERSION }}-darwin-arm64.zip
          draft: false
          prerelease: false
