name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Get version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build binaries
        run: |
          # Build for multiple platforms
          GOOS=linux GOARCH=amd64 go build -o bpl-tools-linux-amd64 .
          GOOS=windows GOARCH=amd64 go build -o bpl-tools-windows-amd64.exe .
          GOOS=darwin GOARCH=amd64 go build -o bpl-tools-darwin-amd64 .
          GOOS=darwin GOARCH=arm64 go build -o bpl-tools-darwin-arm64 .

      - name: Create release packages
        run: |
          # Create temporary directories for each platform
          mkdir -p temp-linux temp-windows temp-darwin-amd64 temp-darwin-arm64

          # Copy and rename binaries to temporary directories
          cp bpl-tools-linux-amd64 temp-linux/bpl-tools
          cp bpl-tools-windows-amd64.exe temp-windows/bpl-tools.exe
          cp bpl-tools-darwin-amd64 temp-darwin-amd64/bpl-tools
          cp bpl-tools-darwin-arm64 temp-darwin-arm64/bpl-tools

          # Create zip archives from temporary directories
          cd temp-linux && zip ../bpl-tools-${{ steps.version.outputs.VERSION }}-linux-amd64.zip bpl-tools && cd ..
          cd temp-windows && zip ../bpl-tools-${{ steps.version.outputs.VERSION }}-windows-amd64.zip bpl-tools.exe && cd ..
          cd temp-darwin-amd64 && zip ../bpl-tools-${{ steps.version.outputs.VERSION }}-darwin-amd64.zip bpl-tools && cd ..
          cd temp-darwin-arm64 && zip ../bpl-tools-${{ steps.version.outputs.VERSION }}-darwin-arm64.zip bpl-tools && cd ..

          # Clean up temporary directories
          rm -rf temp-linux temp-windows temp-darwin-amd64 temp-darwin-arm64

      - name: Generate release notes
        id: release_notes
        run: |
          cat > release_notes.md << 'EOF'
          ## BPL Tools ${{ steps.version.outputs.VERSION }}

          ### Quick Start
          1. Download the appropriate zip file for your platform below
          2. Extract the zip file  
          3. Run the tool: `./bpl-tools` (Linux/macOS) or `bpl-tools.exe` (Windows)
          4. The application will automatically prompt you for any required credentials when you first use each feature

          ### Features
          - **Check Player Names**: Verify player names contain team abbreviations (no credentials required)
          - **Handle Private League Invites**: Automatically process private league invitations  
          - **Guild Stash Monitor**: Monitor guild stash changes and sync to BPL backend

          ### What's New
          - ✨ **Auto-setup**: No manual configuration required! The app will guide you through entering credentials
          - 🔒 **Secure input**: Sensitive values are hidden while typing
          - 💾 **Auto-save**: Credentials are automatically saved for future use
          - 📋 **Built-in instructions**: Step-by-step guides for obtaining each credential
          - 🎯 **Simplified releases**: Just download, extract, and run!

          ### Platform Downloads
          - **Windows**: `bpl-tools-${{ steps.version.outputs.VERSION }}-windows-amd64.zip`
          - **Linux**: `bpl-tools-${{ steps.version.outputs.VERSION }}-linux-amd64.zip`  
          - **macOS Intel**: `bpl-tools-${{ steps.version.outputs.VERSION }}-darwin-amd64.zip`
          - **macOS Apple Silicon**: `bpl-tools-${{ steps.version.outputs.VERSION }}-darwin-arm64.zip`
          EOF

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          name: BPL Tools ${{ steps.version.outputs.VERSION }}
          body_path: release_notes.md
          files: |
            bpl-tools-${{ steps.version.outputs.VERSION }}-linux-amd64.zip
            bpl-tools-${{ steps.version.outputs.VERSION }}-windows-amd64.zip
            bpl-tools-${{ steps.version.outputs.VERSION }}-darwin-amd64.zip
            bpl-tools-${{ steps.version.outputs.VERSION }}-darwin-arm64.zip
          draft: false
          prerelease: false
